apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-readiness-probe
spec:
  containers:
  - name: nginx
    image: nginx:1.19.5
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
