apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox
  labels:
    app: nginx-busybox
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "while true; do date > /html/index.html; sleep 1; done"]
    volumeMounts:
    - name: html
      mountPath: /html
  volumes:
  - name: html
    emptyDir: {}
