apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-container
    image: redis:latest
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: secret-env
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: secret-env
          key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-env
type: Opaque
data:
  username: username
  password: password
